package main

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

// indexCard is a summary row on the faction index page.
type indexCard struct {
	Tag        string
	Name       string
	Treasury   int
	Members    int
	CapturedAt time.Time
}

var indexTemplate = template.Must(template.New("index").Funcs(factionFuncs).Parse(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Faction Dashboards</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap');
  :root{--s0:hsl(222,47%,11%);--s1:hsl(222,47%,14%);--s2:hsl(222,45%,18%);
    --tp:hsl(220,15%,95%);--ts:hsl(220,12%,70%);--tm:hsl(220,10%,50%);--green:hsl(150,70%,55%)}
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'JetBrains Mono',monospace;background:var(--s0);color:var(--ts);padding:2rem}
  .container{max-width:800px;margin:0 auto}
  h1{color:var(--tp);font-size:1.6rem;margin-bottom:1.5rem}
  .card{display:block;background:var(--s1);border:1px solid var(--s2);border-radius:6px;
    padding:1rem 1.25rem;margin-bottom:.75rem;text-decoration:none;color:var(--ts)}
  .card:hover{background:var(--s2)}
  .card .tag{color:var(--green);font-weight:600;font-size:1.1rem}
  .card .name{color:var(--tp)} .card .meta{color:var(--tm);font-size:.8rem;margin-top:.25rem}
  .footer{margin-top:2rem;color:var(--tm);font-size:.8rem}
</style></head><body><div class="container">
<h1>Faction Dashboards</h1>
{{range .}}
<a class="card" href="faction-{{.Tag}}.html">
  <span class="tag">{{.Tag}}</span> <span class="name">{{.Name}}</span>
  <div class="meta">💰 {{comma .Treasury}} · 👥 {{.Members}} members · collected {{.CapturedAt}}</div>
</a>
{{end}}
<div class="footer">Generated by SpaceMolt faction-dashboard</div>
</div></body></html>
`))

// renderIndexHTML renders the faction index page.
func renderIndexHTML(cards []indexCard) (string, error) {
	var buf bytes.Buffer
	if err := indexTemplate.Execute(&buf, cards); err != nil {
		return "", fmt.Errorf("execute index template: %w", err)
	}
	return buf.String(), nil
}
