// Package banker plans and executes credit top-ups for agents that have run dry.
//
// It exists because the fleet has no way to move money. A weekly tax trickle
// drains accounts that cannot replenish, and an agent at zero cannot buy fuel,
// so it strands, is quarantined, and stops existing. On 2026-10-03, 94 of 149
// agents sat below 10,000 credits and eight had been quarantined for up to
// twelve days -- one of them, salvager-4, detained a fortnight over a 675-credit
// bounty, while 28M sat idle in a single trader.
//
// Credits are the only thing this package moves. They reach any agent anywhere,
// landing straight in the wallet; items and ships are station-bound and must be
// collected in person, which is a different problem entirely.
package banker

import (
	"fmt"
	"sort"
	"strings"
)

// Candidate is one agent the sweep considered.
type Candidate struct {
	AgentID string
	// Username is the in-game display name. send_gift addresses THIS, not the
	// agent id, and the two differ for most of the fleet -- names carry spaces,
	// apostrophes and emoji. An empty one means unaddressable, never "use the id".
	Username string
	Fleet    string
	Credits  float64
}

// Grant is a planned payment.
type Grant struct {
	Candidate
	Amount float64
}

// Skip records a candidate that will not be paid, and why.
type Skip struct {
	Candidate
	Reason string
}

// Plan is the full decision for one sweep: what will be paid, what will not,
// and the total. Producing it is pure, so it can be printed for review and then
// executed unchanged.
type Plan struct {
	Grants []Grant
	Skips  []Skip
	Total  float64
}

// PlanTopUp decides who to top up to floor.
//
// maxTotal, when positive, is a hard cap on the sweep. Candidates are funded
// NEEDIEST FIRST because the poorest are the ones closest to debt jail, and a
// grant that does not fit under the cap is skipped whole rather than trimmed:
// a partial top-up leaves an agent short of the floor, which is the state the
// floor exists to prevent.
//
// exclude holds agent ids that must never be paid -- in practice the funding
// agent itself.
func PlanTopUp(cands []Candidate, floor, maxTotal float64, exclude map[string]bool) Plan {
	var p Plan
	if floor <= 0 {
		return p
	}

	// Neediest first. Ties break on agent id so a sweep is reproducible and two
	// dry runs print the same order.
	ordered := make([]Candidate, len(cands))
	copy(ordered, cands)
	sort.SliceStable(ordered, func(i, j int) bool {
		if ordered[i].Credits != ordered[j].Credits {
			return ordered[i].Credits < ordered[j].Credits
		}

		return ordered[i].AgentID < ordered[j].AgentID
	})

	for _, c := range ordered {
		switch {
		case exclude[c.AgentID]:
			p.Skips = append(p.Skips, Skip{Candidate: c, Reason: "funding agent"})
		case c.Credits >= floor:
			// Not recorded as a skip: being solvent is the normal case and
			// listing 55 healthy agents would bury the ones that matter.
			continue
		case c.Username == "":
			p.Skips = append(p.Skips, Skip{Candidate: c, Reason: "no username; send_gift cannot address it"})
		default:
			amount := floor - c.Credits
			if maxTotal > 0 && p.Total+amount > maxTotal {
				p.Skips = append(p.Skips, Skip{Candidate: c, Reason: "would exceed the spend cap"})

				continue
			}
			p.Grants = append(p.Grants, Grant{Candidate: c, Amount: amount})
			p.Total += amount
		}
	}

	return p
}

// Script renders grants as play_as commands.
//
// Execution goes through play_as rather than a second login path inside this
// tool: it already handles the session, command pacing and logging, and every
// line it runs is reviewable before it is run.
//
// Usernames are double-quoted. play_as's SplitArgs is quote-aware, so a double
// quote survives the embedded apostrophes in names like "Blade 'Battler'
// Blackwoo"; a bare name with a space would parse as two arguments and gift to
// the wrong player. A name containing a double quote cannot be expressed this
// way, so it is refused in-line rather than emitted broken.
func Script(grants []Grant) string {
	var b strings.Builder
	b.WriteString("# generated by cmd/tools/banker -- review before running\n")
	for _, g := range grants {
		if strings.Contains(g.Username, `"`) {
			fmt.Fprintf(&b, "# SKIPPED %s: username contains a double quote and cannot be addressed safely\n", g.AgentID)

			continue
		}
		fmt.Fprintf(&b, "send_gift %q credits %.0f\n", g.Username, g.Amount)
	}

	return b.String()
}
