package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// OpenAPI structures (minimal subset needed for tool generation)
type OpenAPISpec struct {
	Paths map[string]PathItem `json:"paths"`
}

type PathItem struct {
	Post *Operation `json:"post"`
	Get  *Operation `json:"get"`
}

type Operation struct {
	OperationID string      `json:"operationId"`
	Description string      `json:"description"`
	RequestBody RequestBody `json:"requestBody"`
}

type RequestBody struct {
	Content map[string]MediaType `json:"content"`
}

type MediaType struct {
	Schema Schema `json:"schema"`
}

type Schema struct {
	Type       string             `json:"type"`
	Properties map[string]Property `json:"properties"`
	Required   []string           `json:"required"`
}

type Property struct {
	Type        string `json:"type"`
	Description string `json:"description"`
	Format      string `json:"format"`
}

// MCPTool represents a tool definition for MCP
type MCPTool struct {
	Name        string
	CommandName string
	Description string
	Properties  map[string]PropertyDef
	Required    []string
}

type PropertyDef struct {
	Type        string
	Description string
}

const toolsTemplate = `// Code generated by generate-mcp-tools. DO NOT EDIT.
package main

// GeneratedTools returns all MCP tool definitions from the OpenAPI spec
func GeneratedTools() []map[string]any {
	return []map[string]any{
{{- range . }}
		{
			"name":        "{{ .Name }}",
			"description": {{ printf "%q" .Description }},
			"inputSchema": map[string]any{
				"type": "object",
				"properties": map[string]any{
{{- range $key, $prop := .Properties }}
					{{ printf "%q" $key }}: map[string]any{
						"type":        {{ printf "%q" $prop.Type }},
						"description": {{ printf "%q" $prop.Description }},
					},
{{- end }}
				},
{{- if .Required }}
				"required": []string{
{{- range .Required }}
					{{ printf "%q" . }},
{{- end }}
				},
{{- end }}
			},
		},
{{- end }}
	}
}
`

func main() {
	inputPath := flag.String("input", "server_docs/openapi.json", "Path to OpenAPI spec")
	outputPath := flag.String("output", "cmd/mcp-ws-bridge/tools_generated.go", "Output Go file")
	flag.Parse()

	// Read OpenAPI spec
	data, err := os.ReadFile(*inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading OpenAPI spec: %v\n", err)
		os.Exit(1)
	}

	var spec OpenAPISpec
	if err := json.Unmarshal(data, &spec); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing OpenAPI spec: %v\n", err)
		os.Exit(1)
	}

	// Extract tool definitions
	tools := extractTools(spec)

	// Sort by name for stable output
	sort.Slice(tools, func(i, j int) bool {
		return tools[i].Name < tools[j].Name
	})

	// Generate Go code
	if err := generateGoCode(tools, *outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d MCP tools -> %s\n", len(tools), *outputPath)
}

func extractTools(spec OpenAPISpec) []MCPTool {
	var tools []MCPTool

	for path, pathItem := range spec.Paths {
		// Remove leading slash
		commandName := strings.TrimPrefix(path, "/")

		var op *Operation
		if pathItem.Post != nil {
			op = pathItem.Post
		} else if pathItem.Get != nil {
			op = pathItem.Get
		}

		if op == nil {
			continue
		}

		// Clean up description (remove example JSON, keep first paragraph)
		description := cleanDescription(op.Description)

		tool := MCPTool{
			Name:        commandName,
			CommandName: commandName,
			Description: description,
			Properties:  make(map[string]PropertyDef),
		}

		// Extract schema from request body
		if content, ok := op.RequestBody.Content["application/json"]; ok {
			schema := content.Schema
			tool.Required = schema.Required

			for propName, prop := range schema.Properties {
				tool.Properties[propName] = PropertyDef{
					Type:        mapJSONType(prop.Type),
					Description: prop.Description,
				}
			}
		}

		tools = append(tools, tool)
	}

	return tools
}

func cleanDescription(desc string) string {
	// Remove example JSON (anything after "**Example:**")
	if idx := strings.Index(desc, "**Example:**"); idx != -1 {
		desc = desc[:idx]
	}

	// Trim whitespace
	desc = strings.TrimSpace(desc)

	// Take first paragraph only (up to double newline)
	if idx := strings.Index(desc, "\n\n"); idx != -1 {
		desc = desc[:idx]
	}

	// Remove newlines within paragraph
	desc = strings.ReplaceAll(desc, "\n", " ")

	// Collapse multiple spaces
	for strings.Contains(desc, "  ") {
		desc = strings.ReplaceAll(desc, "  ", " ")
	}

	return desc
}

func mapJSONType(jsonType string) string {
	switch jsonType {
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return "array"
	case "object":
		return "object"
	default:
		return "string"
	}
}

func generateGoCode(tools []MCPTool, outputPath string) error {
	// Parse template
	tmpl, err := template.New("tools").Parse(toolsTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	// Execute template
	var buf strings.Builder
	if err := tmpl.Execute(&buf, tools); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Format Go code
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		// Write unformatted code for debugging
		_ = os.WriteFile(outputPath+".unformatted", []byte(buf.String()), 0644)
		return fmt.Errorf("formatting Go code: %w (see %s.unformatted)", err, outputPath)
	}

	// Ensure output directory exists
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Write to file
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	return nil
}
